'use client'
import { Plus, ArrowSquareOut, Trash } from '@phosphor-icons/react'
import { newId, safeLink, type ResourceLink, type WorkspaceTask } from '@/lib/workspace/model'
import { Button, Field, inputClass, Empty } from './ui'

export function ResourcesEditor({links,onChange}:{links:ResourceLink[];onChange:(links:ResourceLink[])=>void}){
  const patch=(id:string,value:Partial<ResourceLink>)=>onChange(links.map(l=>l.id===id?{...l,...value}:l))
  return <div className="space-y-5"><p className="text-sm leading-6 text-[#526170]">Logo, Speisekarte, Medienfreigabe oder 360°-Tour verlinken. Die Dateien bleiben bei ihrer Quelle und behalten deren Zugriffsrechte.</p>
    {!links.length?<Empty title="Alles Wichtige griffbereit">Füge den ersten Datei- oder Seitenverweis hinzu.</Empty>:null}
    {links.map((l,index)=><div key={l.id} className="grid gap-3 border-b border-[#061829]/10 pb-5"><div className="grid gap-3 sm:grid-cols-2"><Field label={`Linktitel ${index+1}`}><input className={inputClass} value={l.title} maxLength={200} onChange={e=>patch(l.id,{title:e.target.value})}/></Field><Field label={`Kategorie ${index+1}`}><input className={inputClass} value={l.category} maxLength={100} list="workspace-link-categories" onChange={e=>patch(l.id,{category:e.target.value})}/></Field></div><Field label={`Adresse ${index+1}`}><input className={inputClass} type="url" value={l.url} maxLength={4000} placeholder="https://…" onChange={e=>patch(l.id,{url:e.target.value})}/></Field>{l.url&&!safeLink(l.url)?<p className="text-xs text-red-700">Bitte eine HTTP(S)-Adresse ohne Zugangsdaten eintragen.</p>:null}<Field label={`Notiz zum Link ${index+1}`}><input className={inputClass} value={l.note} maxLength={4000} onChange={e=>patch(l.id,{note:e.target.value})}/></Field><div className="flex gap-3">{safeLink(l.url)?<a href={safeLink(l.url)!} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 py-2 text-sm font-semibold text-[#0671d1]">Öffnen<ArrowSquareOut size={15}/></a>:null}<Button className="ml-auto" aria-label={`Link ${index+1} entfernen`} onClick={()=>onChange(links.filter(item=>item.id!==l.id))}><Trash size={15}/>Entfernen</Button></div></div>)}
    <datalist id="workspace-link-categories">{['Logo','Bilder','Speisekarte','Medienfreigabe','Vertragsunterlage','360°-Tour','Sonstige Datei'].map(c=><option key={c} value={c}/>)}</datalist><Button disabled={links.length>=100} onClick={()=>onChange([...links,{id:newId(),title:'',url:'',category:'Sonstige Datei',note:''}])}><Plus size={16}/>Link hinzufügen</Button>
  </div>
}
export function TasksEditor({tasks,onChange}:{tasks:WorkspaceTask[];onChange:(tasks:WorkspaceTask[])=>void}){
  const patch=(id:string,value:Partial<WorkspaceTask>)=>onChange(tasks.map(t=>t.id===id?{...t,...value}:t))
  return <div className="space-y-5"><p className="text-sm text-[#526170]">{tasks.filter(t=>t.done).length} von {tasks.length} umgesetzt. Eine Vereinbarung ist erst nach Bearbeitung im Admin und Prüfung umgesetzt.</p>
    {tasks.map((t,index)=><div key={t.id} className="border-b border-[#061829]/10 pb-5"><div className="mb-3 flex items-center gap-3"><input aria-label={`Aufgabe ${index+1} erledigt`} type="checkbox" checked={t.done} onChange={e=>patch(t.id,{done:e.target.checked})} className="size-5 accent-[#118cff]"/><strong className="text-xs text-[#526170]">Nächster Schritt {index+1}</strong><Button className="ml-auto" aria-label={`Aufgabe ${index+1} entfernen`} onClick={()=>onChange(tasks.filter(item=>item.id!==t.id))}><Trash size={14}/></Button></div><Field label={`Aufgabe ${index+1}`}><textarea className={inputClass} value={t.text} maxLength={2000} onChange={e=>patch(t.id,{text:e.target.value})}/></Field><div className="my-3 grid gap-3 sm:grid-cols-2"><Field label={`Verantwortlich ${index+1}`}><input className={inputClass} value={t.owner} maxLength={200} onChange={e=>patch(t.id,{owner:e.target.value})}/></Field><Field label={`Fällig am ${index+1}`}><input className={inputClass} type="date" value={t.dueDate} onChange={e=>patch(t.id,{dueDate:e.target.value})}/></Field></div><Field label={`Umsetzungsnachweis ${index+1}`} hint="Was wurde wann und durch wen geprüft?"><textarea className={inputClass} value={t.evidence} maxLength={4000} onChange={e=>patch(t.id,{evidence:e.target.value})}/></Field></div>)}
    <Button disabled={tasks.length>=200} onClick={()=>onChange([...tasks,{id:newId(),text:'',owner:'',dueDate:'',done:false,evidence:''}])}><Plus size={16}/>Aufgabe hinzufügen</Button>
  </div>
}
