import { loadWorkspaceIndex, loadWorkspacePages, loadWorkspacePage, saveWorkspacePage, saveWorkspace, setWorkspaceFavorite, loadWorkspaceVersions, restoreWorkspacePage, findWorkspacePartners, loadWorkspacePartnerBrief } from '@/app/workspace/actions'
export const workspaceServices={loadWorkspaceIndex,loadWorkspacePages,loadWorkspacePage,saveWorkspacePage,saveWorkspace,setWorkspaceFavorite,loadWorkspaceVersions,restoreWorkspacePage,findWorkspacePartners,loadWorkspacePartnerBrief}
export type WorkspaceServices=typeof workspaceServices
