import { loadWorkspacePartnerDetails, saveWorkspacePartnerDetail, addWorkspacePartnerDetail } from '@/app/workspace/partner-edit-actions'
import { loadWorkspaceIndex, loadWorkspacePages, loadWorkspacePage, saveWorkspacePage, saveWorkspace, setWorkspaceFavorite, loadWorkspaceVersions, restoreWorkspacePage, findWorkspacePartners, loadWorkspacePartnerBrief } from '@/app/workspace/actions'
export const workspaceServices={loadWorkspacePartnerDetails,saveWorkspacePartnerDetail,addWorkspacePartnerDetail,loadWorkspaceIndex,loadWorkspacePages,loadWorkspacePage,saveWorkspacePage,saveWorkspace,setWorkspaceFavorite,loadWorkspaceVersions,restoreWorkspacePage,findWorkspacePartners,loadWorkspacePartnerBrief}
export type WorkspaceServices=typeof workspaceServices
