'use client'
import { useCallback, useEffect, useRef, useState } from 'react'
import { Archive, ArrowRight, ChatCircleText, FileText, FolderSimple, Kanban, List, MagnifyingGlass, Plus, Star, Table } from '@phosphor-icons/react'
import { makePage, newId, pageFromTemplate, pageKinds, pageStatuses, type ActionResult, type PageKind, type PageMeta, type Workspace, type WorkspacePage } from '@/lib/workspace/model'
import { onboardingContent } from '@/lib/workspace/templates'
import type { PageFilter } from '@/app/workspace/actions'
import { workspaceServices, type WorkspaceServices } from './services'
import { WorkspaceEditor } from './workspace-editor'
import { Button, Field, inputClass, Empty } from './ui'

type Index={workspaces:Workspace[];favorites:string[]}
type Props={initial:ActionResult<Index>;initialPageId?:string;initialPartnerId?:string;services?:WorkspaceServices}
export function WorkspaceApp({initial,initialPageId,initialPartnerId,services=workspaceServices}:Props){
  const [workspaces,setWorkspaces]=useState(initial.ok?initial.value.workspaces:[]),[favorites,setFavorites]=useState(initial.ok?initial.value.favorites:[])
  const [workspaceId,setWorkspaceId]=useState(initial.ok?initial.value.workspaces.find(w=>!w.archived)?.id??initial.value.workspaces[0]?.id??'':'')
  const [pages,setPages]=useState<PageMeta[]>([]),[total,setTotal]=useState(0),[selected,setSelected]=useState<WorkspacePage|null>(null),[epoch,setEpoch]=useState(0)
  const [partnerContextId,setPartnerContextId]=useState(initialPartnerId)
  const [filter,setFilter]=useState<PageFilter>({partnerId:initialPartnerId}),[favoriteOnly,setFavoriteOnly]=useState(false),[view,setView]=useState<'tree'|'table'|'board'>('tree')
  const [query,setQuery]=useState(''),[error,setError]=useState(initial.ok?'':initial.error),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false)
  const [workspaceForm,setWorkspaceForm]=useState<'create'|'edit'|null>(null),[name,setName]=useState(''),[description,setDescription]=useState(''),[showArchivedWorkspaces,setShowArchivedWorkspaces]=useState(false),[createKind,setCreateKind]=useState<PageKind>('note')
  const guard=useRef<()=>Promise<boolean>>(async()=>true),requestId=useRef(0),started=useRef(false),creating=useRef(false),workspaceRequestId=useRef<string|null>(null)
  const [editingWorkspace,setEditingWorkspace]=useState<Workspace|null>(null)
  const pendingCreate=useRef<{key:string;page:WorkspacePage}|null>(null)
  const active=workspaces.find(w=>w.id===workspaceId)
  const setGuard=useCallback((fn:()=>Promise<boolean>)=>{guard.current=fn},[])
  const stored=useCallback((page:WorkspacePage)=>{setPages(old=>[page,...old.filter(p=>p.id!==page.id)]);setSelected(old=>old?.id===page.id?page:old)},[])
  const replace=useCallback((page:WorkspacePage)=>{setPages(old=>[page,...old.filter(p=>p.id!==page.id)]);setSelected(page);setWorkspaceId(page.workspace_id);setEpoch(v=>v+1);window.history.replaceState(null,'',`/workspace?page=${page.id}`)},[])
  const run=async(fn:()=>Promise<void>)=>{if(busy)return;setBusy(true);setError('');try{await fn()}catch{setError('Die Aktion ist fehlgeschlagen. Bitte erneut versuchen.')}finally{setBusy(false)}}
  const fetchPages=useCallback(async(id:string,filters:PageFilter,offset=0)=>{
    const token=++requestId.current;setLoading(true)
    try{const result=await services.loadWorkspacePages(id,filters,offset);if(token!==requestId.current)return;if(result.ok){setPages(old=>offset?[...old,...result.value.pages.filter(p=>!old.some(v=>v.id===p.id))]:result.value.pages);setTotal(result.value.total)}else setError(result.error)}catch{if(token===requestId.current)setError('Die Seiten konnten nicht geladen werden. Bitte erneut versuchen.')}
    finally{if(token===requestId.current)setLoading(false)}
  },[services])
  useEffect(()=>{const timer=setTimeout(()=>setFilter(old=>({...old,query})),250);return()=>clearTimeout(timer)},[query])
  useEffect(()=>{const timer=setTimeout(()=>{if(workspaceId)void fetchPages(workspaceId,filter)},0);return()=>clearTimeout(timer)},[workspaceId,filter,fetchPages])
  useEffect(()=>{if(started.current||!initialPageId)return;started.current=true;services.loadWorkspacePage(initialPageId).then(result=>{if(result.ok)replace(result.value);else setError(result.error)}).catch(()=>setError('Die verlinkte Seite konnte nicht geladen werden.'))},[initialPageId,replace,services])
  const openPage=async(id:string)=>{if(!await guard.current())return;const result=await services.loadWorkspacePage(id);if(result.ok)replace(result.value);else setError(result.error)}
  const switchWorkspace=async(id:string)=>{if(!await guard.current())return;setSelected(null);setWorkspaceId(id);setPages([]);setFilter({});setQuery('');window.history.replaceState(null,'','/workspace')}
  const create=async(kind:PageKind,parent?:PageMeta,source?:WorkspacePage)=>{
    if(creating.current||!workspaceId)return
    creating.current=true
    try{
      if(!await guard.current())return
      const key=[workspaceId,kind,parent?.id,source?.id,partnerContextId].join(':')
      const draft=pendingCreate.current?.key===key?pendingCreate.current.page:source?pageFromTemplate(source,workspaceId,kind):makePage(workspaceId,kind,parent)
      if(!source&&kind==='conversation'&&!draft.content.questions.length)draft.content=onboardingContent()
      if(!parent&&partnerContextId)draft.partner_id=partnerContextId
      if(kind==='partner'&&draft.partner_id){const partner=await services.findWorkspacePartners('',draft.partner_id);if(partner.ok&&partner.value[0])draft.title=partner.value[0].name}
      pendingCreate.current={key,page:draft}
      const result=await services.saveWorkspacePage(draft)
      if(result.ok){pendingCreate.current=null;replace(result.value)}else setError(result.error)
    }finally{creating.current=false}
  }
  const favorite=async()=>{if(!selected)return;const next=!favorites.includes(selected.id),result=await services.setWorkspaceFavorite(selected.id,next);if(result.ok)setFavorites(old=>next?[...old,selected.id]:old.filter(id=>id!==selected.id));else setError(result.error)}
  const visible=pages.filter(p=>p.archived===(filter.archived===true)&&(!favoriteOnly||favorites.includes(p.id)))
  const depth=(page:PageMeta)=>{let parent=page.parent_id,level=0;const seen=new Set([page.id]);while(parent&&level<7&&!seen.has(parent)){seen.add(parent);level++;parent=pages.find(p=>p.id===parent)?.parent_id??null}return level}
  const ordered:PageMeta[]=[];const remaining=new Set(visible.map(p=>p.id));const visit=(p:PageMeta)=>{if(!remaining.delete(p.id))return;ordered.push(p);visible.filter(child=>child.parent_id===p.id).forEach(visit)};visible.filter(p=>!p.parent_id||!remaining.has(p.parent_id)).forEach(visit);visible.forEach(visit)
  const saveWorkspaceForm=async()=>{
    if(!await guard.current())return
    const id=workspaceForm==='edit'&&editingWorkspace?editingWorkspace.id:workspaceRequestId.current??newId();workspaceRequestId.current=id
    const result=await services.saveWorkspace({id,revision:workspaceForm==='edit'&&editingWorkspace?editingWorkspace.revision:0,title:name,description,archived:workspaceForm==='edit'&&editingWorkspace?editingWorkspace.archived:false})
    if(result.ok){setWorkspaces(old=>[...old.filter(w=>w.id!==id),result.value]);setWorkspaceForm(null);workspaceRequestId.current=null;await switchWorkspace(id)}else setError(result.error)
  }
  const row=(p:PageMeta)=><button key={p.id} onClick={()=>void run(()=>openPage(p.id))} className="group flex w-full items-center gap-3 border-b border-[#061829]/[.07] px-4 py-4 text-left hover:bg-[#f3f8ff] sm:px-6" style={view==='tree'?{paddingLeft:24+depth(p)*18}:undefined}><FileText size={18} className="shrink-0 text-[#697680]"/><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold">{p.title}</span><span className="mt-1 block truncate text-xs text-[#697680]">{pageKinds[p.kind]}{p.owner?` · ${p.owner}`:''}{p.tags.filter(Boolean).length?` · ${p.tags.filter(Boolean).join(', ')}`:''}</span></span>{favorites.includes(p.id)?<Star size={14} weight="fill" className="text-[#0671d1]"/>:null}<span className="hidden text-xs text-[#526170] sm:block">{pageStatuses[p.status]}</span><ArrowRight size={16} className="shrink-0 text-[#697680]"/></button>
  return <div data-admin-i18n-ignore="true" className="mx-auto max-w-[1600px] text-[#061829]">
    {error?<div role="alert" className="mb-4 rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-950"><p>{error}</p><Button className="mt-3" onClick={()=>void run(async()=>{const result=await services.loadWorkspaceIndex();if(result.ok){setWorkspaces(result.value.workspaces);setFavorites(result.value.favorites);setError('');if(workspaceId)await fetchPages(workspaceId,filter)}else setError(result.error)})}>Erneut laden</Button></div>:null}
    <div className="grid min-w-0 items-start gap-5 lg:grid-cols-[225px_minmax(0,1fr)]">
      <aside className="rounded-2xl border border-[#061829]/10 bg-white p-4 lg:sticky lg:top-5">
        <div className="mb-5 flex items-center gap-2"><FolderSimple size={20} weight="duotone" className="text-[#0671d1]"/><span className="font-bold">Arbeitsbereiche</span></div>
        <nav aria-label="Arbeitsbereiche" className="space-y-1">{workspaces.filter(w=>showArchivedWorkspaces||!w.archived).map(w=><button key={w.id} type="button" onClick={()=>void run(()=>switchWorkspace(w.id))} aria-current={w.id===workspaceId?'page':undefined} className={`flex w-full items-center gap-2 rounded-lg px-3 py-3 text-left text-sm ${w.id===workspaceId?'bg-[#edf5fd] font-semibold text-[#0671d1]':'text-[#526170] hover:bg-zinc-50'}`}><span className="min-w-0 flex-1 truncate">{w.title}</span>{w.archived?<Archive size={13}/>:null}</button>)}</nav>
        <Button className="mt-3 w-full" onClick={()=>{setWorkspaceForm('create');setName('');setDescription('');workspaceRequestId.current=null}}><Plus size={15}/>Arbeitsbereich</Button>
        <label className="mt-4 flex items-center gap-2 text-xs text-[#697680]"><input type="checkbox" checked={showArchivedWorkspaces} onChange={e=>setShowArchivedWorkspaces(e.target.checked)}/>Archivierte anzeigen</label>
        <div className="mt-6 border-t border-[#061829]/10 pt-5"><p className="mb-3 text-[11px] font-bold uppercase tracking-wider text-[#697680]">Dein Überblick</p><button type="button" onClick={()=>setFavoriteOnly(v=>!v)} aria-pressed={favoriteOnly} className={`flex w-full items-center gap-2 rounded-lg px-2 py-2 text-sm ${favoriteOnly?'bg-[#edf5fd] text-[#0671d1]':'text-[#526170]'}`}><Star size={16}/>Favoriten</button><button type="button" onClick={()=>setFilter(old=>({...old,archived:!old.archived}))} aria-pressed={filter.archived===true} className={`flex w-full items-center gap-2 rounded-lg px-2 py-2 text-sm ${filter.archived?'bg-[#edf5fd] text-[#0671d1]':'text-[#526170]'}`}><Archive size={16}/>Archiv</button></div>
        <a href="/wissen" className="mt-6 block border-t border-[#061829]/10 pt-4 text-xs font-semibold text-[#526170]">Wissensspiegel öffnen →</a>
        <p className="mt-3 text-xs leading-5 text-[#697680]">Intern für berechtigte Admins.</p>
      </aside>
      <div className="min-w-0">
        {workspaceForm?<form className="mb-5 space-y-4 rounded-2xl border border-[#061829]/10 bg-white p-5" onSubmit={e=>{e.preventDefault();void run(saveWorkspaceForm)}}><h2 className="text-lg font-bold">{workspaceForm==='create'?'Arbeitsbereich erstellen':'Arbeitsbereich bearbeiten'}</h2><Field label="Name"><input className={inputClass} required maxLength={200} value={name} onChange={e=>setName(e.target.value)} autoFocus/></Field><Field label="Beschreibung"><textarea className={inputClass} maxLength={4000} value={description} onChange={e=>setDescription(e.target.value)}/></Field><div className="flex gap-2"><Button type="submit" disabled={busy}>Speichern</Button><Button onClick={()=>setWorkspaceForm(null)}>Abbrechen</Button></div></form>:null}
        {selected?<WorkspaceEditor key={`${selected.id}:${epoch}`} page={selected} pages={pages} favorite={favorites.includes(selected.id)} services={services} externalBusy={busy} onStored={stored} onReplace={replace} onFavorite={()=>void run(favorite)} onCreate={create} setGuard={setGuard} onBack={()=>void run(async()=>{if(await guard.current()){setSelected(null);window.history.replaceState(null,'','/workspace');await fetchPages(workspaceId,filter)}})}/>:<>
          <div className="mb-5 flex flex-wrap items-start gap-4"><div className="min-w-0 flex-1"><p className="mb-2 text-[11px] font-bold uppercase tracking-[.16em] text-[#697680]">Notieren. Besprechen. Umsetzen.</p><h1 className="text-3xl font-bold tracking-tight">{active?.title??'Platz für deine Ideen'}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#526170]">{active?.description||'Halte Wissen fest und gehe vorbereitet in jedes Partnergespräch.'}</p></div>{active?<details className="relative"><summary className="cursor-pointer rounded-lg border border-[#061829]/15 bg-white px-3 py-2.5 text-sm font-semibold">Arbeitsbereich verwalten</summary><div className="absolute right-0 z-20 mt-1 grid w-60 gap-2 rounded-xl border bg-white p-2 shadow-lg"><Button onClick={()=>{setWorkspaceForm('edit');setEditingWorkspace(active);setName(active.title);setDescription(active.description)}}>Umbenennen & Beschreibung</Button><Button onClick={()=>void run(async()=>{const result=await services.saveWorkspace({...active,archived:!active.archived});if(result.ok){setWorkspaces(old=>old.map(w=>w.id===active.id?result.value:w));if(result.value.archived)setShowArchivedWorkspaces(true)}else setError(result.error)})}>{active.archived?'Wiederherstellen':'Archivieren'}</Button></div></details>:null}</div>
          {partnerContextId?<div className="mb-4 flex flex-wrap items-center gap-3 rounded-xl bg-[#edf5fd] p-4 text-sm"><ChatCircleText size={20}/><span className="mr-auto">Partnerbezug ist vorausgewählt.</span><Button disabled={!active||busy} onClick={()=>void run(()=>create('partner'))}>Partnerakte anlegen</Button><Button onClick={()=>{setPartnerContextId(undefined);setFilter(old=>({...old,partnerId:undefined}));window.history.replaceState(null,'','/workspace')}}>Alle Seiten anzeigen</Button></div>:null}
          {!active?<div className="rounded-2xl border border-[#061829]/10 bg-white"><Empty title="Dein erster Arbeitsbereich"><p>Erstelle einen Arbeitsbereich für Notizen, Produktideen und Partnerakten. Neue Gespräche können direkt mit dem ausgearbeiteten Leitfaden beginnen.</p><Button className="mt-5" onClick={()=>{setWorkspaceForm('create');setName('Benefitsi');setDescription('Notizen, Ideen und Partnergespräche');workspaceRequestId.current=null}}><Plus size={16}/>Arbeitsbereich erstellen</Button></Empty></div>:<>
            <div className="mb-4 flex flex-wrap gap-2"><select aria-label="Neue Seite als" className={`${inputClass} !w-auto`} value={createKind} onChange={e=>setCreateKind(e.target.value as PageKind)}>{Object.entries(pageKinds).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><Button disabled={busy||active.archived} onClick={()=>void run(()=>create(createKind))} className="!border-[#118cff] !bg-[#118cff] !text-white"><Plus size={16}/>Neue Seite</Button><div className="ml-auto flex gap-1">{([['tree',List,'Seitenbaum'],['table',Table,'Tabelle'],['board',Kanban,'Board']] as const).map(([v,Icon,label])=><Button key={v} aria-label={label} aria-pressed={view===v} className={view===v?'!bg-[#edf5fd]':''} onClick={()=>setView(v)}><Icon size={17}/></Button>)}</div></div>
            <div className="mb-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-[minmax(0,1.8fr)_1fr_1fr_1fr]"><label className="relative"><span className="sr-only">Seiten und Antworten durchsuchen</span><MagnifyingGlass className="absolute left-3 top-3.5 text-[#697680]" size={17}/><input className={`${inputClass} pl-10`} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Notizen & Antworten durchsuchen"/></label><select aria-label="Seitentyp filtern" className={inputClass} value={filter.kind??''} onChange={e=>setFilter(old=>({...old,kind:e.target.value}))}><option value="">Alle Seitentypen</option>{Object.entries(pageKinds).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select aria-label="Status filtern" className={inputClass} value={filter.status??''} onChange={e=>setFilter(old=>({...old,status:e.target.value}))}><option value="">Alle Status</option>{Object.entries(pageStatuses).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><input aria-label="Nach Tag filtern" className={inputClass} value={filter.tag??''} onChange={e=>setFilter(old=>({...old,tag:e.target.value}))} placeholder="Tag filtern"/></div>
            {loading?<div role="status" className="mb-3 space-y-3 rounded-xl border bg-white p-5"><p className="text-xs text-[#526170]">Seiten werden geladen …</p><div className="h-3 w-3/4 rounded bg-zinc-100"/><div className="h-3 w-1/2 rounded bg-zinc-100"/></div>:null}
            {!loading&&!visible.length?<div className="rounded-2xl border border-[#061829]/10 bg-white"><Empty title={filter.archived?'Das Archiv ist leer':'Hier beginnt die nächste gute Idee'}><p>{pages.length?'Für diese Auswahl wurden keine Seiten gefunden.':'Lege eine Notiz, eine Idee oder eine Partnerakte an.'}</p><Button className="mt-4" disabled={active.archived||busy} onClick={()=>void run(()=>create('conversation'))}><ChatCircleText size={16}/>Gespräch mit Leitfaden</Button></Empty></div>:null}
            {view==='tree'?<div className="overflow-hidden rounded-2xl border border-[#061829]/10 bg-white">{ordered.map(row)}</div>:null}
            {view==='table'&&visible.length?<div className="overflow-x-auto rounded-2xl border border-[#061829]/10 bg-white"><table className="w-full text-left text-sm"><thead className="bg-[#f7f6f1] text-xs text-[#697680]"><tr>{['Seite','Typ','Status','Verantwortlich','Termin'].map(h=><th className="px-4 py-3 font-semibold" key={h}>{h}</th>)}</tr></thead><tbody>{visible.map(p=><tr key={p.id} className="border-t border-[#061829]/10"><td className="px-4 py-3"><button onClick={()=>void run(()=>openPage(p.id))} className="font-semibold text-[#0671d1]">{p.title}</button></td><td className="whitespace-nowrap px-4 py-3 text-xs">{pageKinds[p.kind]}</td><td className="whitespace-nowrap px-4 py-3 text-xs">{pageStatuses[p.status]}</td><td className="px-4 py-3 text-xs">{p.owner||'—'}</td><td className="whitespace-nowrap px-4 py-3 text-xs">{p.due_date||'—'}</td></tr>)}</tbody></table></div>:null}
            {view==='board'?<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{Object.entries(pageStatuses).map(([status,label])=><section key={status} className="min-w-0 rounded-xl bg-[#eeede8] p-3"><h3 className="mb-3 flex justify-between text-xs font-bold text-[#526170]">{label}<span>{visible.filter(p=>p.status===status).length}</span></h3><div className="space-y-3">{visible.filter(p=>p.status===status).map(p=><article key={p.id} className="rounded-lg border border-[#061829]/10 bg-white p-3"><button onClick={()=>void run(()=>openPage(p.id))} className="mb-2 block text-left text-sm font-semibold">{p.title}</button><p className="mb-3 text-xs text-[#697680]">{pageKinds[p.kind]}{p.due_date?` · ${p.due_date}`:''}</p><select aria-label={`Status für ${p.title}`} className={`${inputClass} !text-xs`} value={p.status} disabled={busy} onChange={e=>{const next=e.target.value as WorkspacePage['status'];void run(async()=>{const read=await services.loadWorkspacePage(p.id);if(!read.ok){setError(read.error);return}if(read.value.revision!==p.revision){setError('Diese Karte wurde inzwischen geändert. Bitte neu laden.');return}const result=await services.saveWorkspacePage({...read.value,status:next});if(result.ok)stored(result.value);else setError(result.error)})}}>{Object.entries(pageStatuses).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></article>)}</div></section>)}</div>:null}
            <div className="mt-4 flex items-center gap-3 text-xs text-[#697680]"><span>{pages.length} von {total} Seiten geladen{favoriteOnly?' · Favoriten aus geladenen Seiten':''}</span>{pages.length<total?<Button disabled={loading} onClick={()=>void fetchPages(workspaceId,filter,pages.length)}>Weitere Seiten</Button>:null}<Button className="ml-auto" disabled={loading} onClick={()=>void fetchPages(workspaceId,filter)}>Aktualisieren</Button></div>
          </>}
        </>}
      </div>
    </div>
  </div>
}
