import type { Metadata } from "next"
import type { ReactNode } from "react"
import Link from "next/link"
import { notFound } from "next/navigation"
import { AdminShell } from "@/app/admin-shell"
import { FieldModeSelect } from "@/components/city-pages/field-mode-select"
import { NavigationEditor, SurfaceEntityPicker } from "@/components/city-pages/surface-editor-controls"
import { PendingSubmitButton } from "@/components/pending-submit-button"
import { requireAdmin } from "@/lib/admin"
import { isCitySurfaceType, loadCitySurfaceEditor, sectionOptions, surfaceLabels, cityCollectionSurfaceKeys, cityHubSurfaceKeys, type CitySafeTargetOption, type CitySurfaceType } from "@/lib/city-pages/surface-configs"
import { restoreCitySurfaceField, saveCitySurface } from "@/app/city-pages/[citySlug]/site/[surface]/actions"

export const dynamic = "force-dynamic"
export const metadata: Metadata = { title: "City Site Editor", description: "Homepage, Hubs, Collections und Navigation des City-Portals verwalten." }

type SearchParams = { key?: string; success?: string; error?: string }
const inputClass = "min-h-11 w-full rounded-xl border border-[#061829]/12 bg-white px-3 text-sm font-semibold text-[#061829] outline-none transition placeholder:text-[#91a0ac] focus:border-[#118cff] focus:ring-2 focus:ring-[#118cff]/10"
const primaryButton = "inline-flex min-h-11 items-center justify-center rounded-xl bg-[#118cff] px-4 text-sm font-black text-white shadow-[0_10px_22px_rgba(17,140,255,.16)] transition hover:bg-[#0878df]"
const secondaryButton = "inline-flex min-h-11 items-center justify-center rounded-xl border border-[#061829]/12 bg-white px-4 text-sm font-black text-[#061829] transition hover:border-[#118cff]/45 hover:bg-[#f3f8ff]"

export default async function CitySurfaceEditorPage({ params, searchParams }: { params: Promise<{ citySlug: string; surface: string }>; searchParams: Promise<SearchParams> }) {
  const route = await params
  const query = await searchParams
  if (!isCitySurfaceType(route.surface)) notFound()
  const { adminSession } = await requireAdmin()
  const editor = await loadCitySurfaceEditor(route.citySlug, route.surface, query.key)
  if (!editor) notFound()
  const adminName = adminSession.profile?.display_name || adminSession.profile?.email || adminSession.user.email || "Admin"
  const config = editor.config
  const scopeLinks = route.surface === "hubs" ? cityHubSurfaceKeys.map((key) => ({ key, label: key === "current" ? "Aktuell" : key === "discovery" ? "Entdecken & Erleben" : key === "events-community" ? "Events & Community" : key === "routes-guides" ? "Touren & Guides" : key === "city-service" ? "Stadt & Service" : "Vorteile" })) : route.surface === "collections" ? cityCollectionSurfaceKeys.map((key) => ({ key, label: key.replaceAll("-", " ") })) : []
  const previewPath = previewUrl(editor.city.slug, editor.scopeType, editor.scopeKey)
  const sectionKeys = sectionOptions(route.surface)
  const selectedRefs = config?.featured_refs ?? []
  const selectedGuides = config?.guide_relation_ids ?? []
  const relatedCollections = config?.related_collection_slugs ?? []
  const targetKey = config?.primary_cta_target?.key ?? ""
  const isNavigation = route.surface === "navigation"

  return <AdminShell adminName={adminName} title={`${surfaceLabels[route.surface]} · ${editor.city.name}`} subtitle="Strukturierte City-Redaktion ohne freien Page Builder">
    <div className="flex flex-wrap items-center justify-between gap-3">
      <Link href={`/city-pages/${editor.city.slug}`} className="text-sm font-black text-[#0b75d9] hover:text-[#075eae]">← Zur City-Übersicht</Link>
      <div className="flex flex-wrap gap-2"><a href={previewPath} target="_blank" rel="noreferrer" className={secondaryButton}>Live-Vorschau öffnen</a>{config ? <Link href={`/media?city=${encodeURIComponent(editor.city.slug)}&entityType=${mediaEntityType(editor.scopeType)}&entityId=${encodeURIComponent(config.id)}`} className={secondaryButton}>Hero-Media öffnen</Link> : null}</div>
    </div>
    {scopeLinks.length ? <div className="flex gap-2 overflow-x-auto pb-1">{scopeLinks.map((item) => <Link key={item.key} href={`/city-pages/${editor.city.slug}/site/${route.surface}?key=${encodeURIComponent(item.key)}`} className={`shrink-0 rounded-full border px-3 py-2 text-xs font-black ${item.key === editor.scopeKey ? "border-[#118cff] bg-[#eef6ff] text-[#086fcc]" : "border-[#061829]/12 bg-white text-[#617080]"}`}>{item.label}</Link>)}</div> : null}
    {query.success ? <Feedback success code={query.success} /> : null}
    {query.error ? <Feedback code={query.error} /> : null}

    <section className="grid overflow-hidden rounded-3xl border border-[#061829]/10 bg-[#061829] text-white sm:grid-cols-3">
      <Metric label="Bereich" value={surfaceLabels[route.surface]} /><Metric label="Datenquelle" value={config ? (config.status === "ACTIVE" ? "Aktiv" : "Entwurf") : "Fallback"} /><Metric label="Letzte Änderung" value={config ? formatDate(config.updated_at) : "Noch nicht gespeichert"} />
    </section>

    <form action={saveCitySurface} className="overflow-hidden rounded-3xl border border-[#061829]/10 bg-white shadow-[0_18px_50px_rgba(6,24,41,.05)]">
      <input type="hidden" name="citySlug" value={editor.city.slug} /><input type="hidden" name="surface" value={route.surface} /><input type="hidden" name="scopeKey" value={editor.scopeKey} />
      <div className="border-b border-[#061829]/10 p-5 sm:p-6"><p className="text-xs font-black uppercase tracking-[.16em] text-[#0b75d9]">{editor.scopeType} · {editor.scopeKey}</p><h2 className="mt-1 text-2xl font-black tracking-[-.035em]">Bestehende Struktur redaktionell steuern</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[#617080]">Die Vorlage, Blocktypen und Sicherheitsregeln bleiben fest. Du steuerst nur die dafür vorgesehenen Felder und Referenzen.</p></div>
      {!isNavigation ? <>
        <div className="grid gap-5 p-5 sm:grid-cols-2 sm:p-6">
          <ControlledField label="Titel" field="title" editor={editor}><input name="title" defaultValue={config?.title ?? ""} maxLength={240} className={inputClass} placeholder="z. B. Sehenswürdigkeiten in Annweiler" /></ControlledField>
          <ControlledField label="Eyebrow / Chip" field="eyebrow" editor={editor}><input name="eyebrow" defaultValue={config?.eyebrow ?? ""} maxLength={180} className={inputClass} placeholder="Entdecken & Erleben" /></ControlledField>
          <ControlledField label="Subtitle" field="subtitle" editor={editor}><input name="subtitle" defaultValue={config?.subtitle ?? ""} maxLength={500} className={inputClass} placeholder="Kurze Einordnung für den Einstieg" /></ControlledField>
          <ControlledField label="Haupt-CTA Label" field="primary_cta_label" editor={editor}><input name="primary_cta_label" defaultValue={config?.primary_cta_label ?? ""} maxLength={120} className={inputClass} placeholder="Heute entdecken" /></ControlledField>
        </div>
        <div className="grid gap-5 border-t border-[#061829]/10 p-5 sm:p-6"><ControlledField label="Beschreibung / Introtext" field="description" editor={editor}><textarea name="description" defaultValue={config?.description ?? ""} maxLength={5000} rows={5} className={`${inputClass} py-3 leading-6`} placeholder="Worum geht es in diesem Bereich?" /></ControlledField></div>
        <section className="border-t border-[#061829]/10 p-5 sm:p-6"><SectionTitle title="CTA und Auffindbarkeit" copy="Ziele werden aus gültigen City-Zielen ausgewählt. Freie interne URLs sind nicht möglich." /><div className="mt-4 grid gap-5 sm:grid-cols-2"><ControlledField label="CTA-Ziel" field="primary_cta_target" editor={editor}><select name="primary_cta_target_key" defaultValue={targetKey} className={inputClass}><option value="">Kein Ziel</option>{groupedTargets(editor.targetOptions)}</select></ControlledField><ControlledField label="Index Policy" field="index_policy" editor={editor}><select name="index_policy" defaultValue={config?.index_policy ?? "index"} className={inputClass}><option value="index">Indexierbar, wenn die City veröffentlicht ist</option><option value="noindex">Nicht indexieren</option></select></ControlledField><ControlledField label="SEO-Titel" field="seo_title" editor={editor}><input name="seo_title" defaultValue={config?.seo_title ?? ""} maxLength={180} className={inputClass} placeholder="Optionaler eigener SEO-Titel" /></ControlledField><ControlledField label="Meta Description" field="seo_description" editor={editor}><textarea name="seo_description" defaultValue={config?.seo_description ?? ""} maxLength={500} rows={3} className={`${inputClass} py-3`} placeholder="Optionaler eigener Meta-Text" /></ControlledField><ControlledField label="Hero-Bild Alt-Text" field="hero_image_alt" editor={editor}><input name="hero_image_alt" defaultValue={config?.hero_image_alt ?? ""} maxLength={300} className={inputClass} placeholder="Beschreibung des Bildes" /></ControlledField></div><p className="mt-4 rounded-xl bg-[#f3f8ff] px-3 py-2 text-xs font-semibold leading-5 text-[#526170]">Hero-Bild selbst wird über die Media Library zugewiesen. Damit bleiben Asset-Status, Focal Point und Rechte an einer Stelle.</p></section>
        <section className="border-t border-[#061829]/10 p-5 sm:p-6"><SectionTitle title="Sichtbare Sektionen" copy="Nur vorhandene, validierte Blöcke. Keine freien Section Types." /><input type="hidden" name="section_visibility" value={JSON.stringify(sectionKeys.filter((key) => config?.section_visibility[key] !== false))} /><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{sectionKeys.map((key) => <label key={key} className="flex min-h-11 items-center gap-3 rounded-xl border border-[#061829]/10 bg-[#fafcfb] px-3 text-sm font-bold"><input type="checkbox" name="section_selection" value={key} defaultChecked={config?.section_visibility[key] !== false} className="size-4 accent-[#118cff]" />{prettyKey(key)}</label>)}</div></section>
        {route.surface === "collections" ? <section className="border-t border-[#061829]/10 p-5 sm:p-6"><SectionTitle title="Sichtbare Filter" copy="Nur die bestehenden Collection-Filter. Die Auswahl blendet keine neuen Blocktypen ein." /><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{filterOptions.map((option) => <label key={option.key} className="flex min-h-11 items-center gap-3 rounded-xl border border-[#061829]/10 bg-[#fafcfb] px-3 text-sm font-bold"><input type="checkbox" name="filter_selection" value={option.key} defaultChecked={config?.filter_visibility[option.key] !== false} className="size-4 accent-[#118cff]" />{option.label}</label>)}</div></section> : null}
        <section className="border-t border-[#061829]/10 p-5 sm:p-6"><SectionTitle title="Featured Inhalte" copy="Suche nach Name, Typ und Ort. Die Auswahl wird als sichere Reihenfolge gespeichert." /><div className="mt-4"><SurfaceEntityPicker name="featured_refs" options={editor.entityOptions} initial={selectedRefs} /></div></section>
        <section className="border-t border-[#061829]/10 p-5 sm:p-6"><SectionTitle title="Verknüpfte Collections und Guides" /><div className="mt-4 grid gap-5 sm:grid-cols-2"><label className="text-xs font-black text-[#526170]">Related Collections<select multiple name="related_collection_slugs" defaultValue={relatedCollections} className="mt-2 min-h-40 w-full rounded-xl border border-[#061829]/12 bg-white p-2 text-sm font-semibold outline-none focus:border-[#118cff]">{cityCollectionOptions()}</select></label><label className="text-xs font-black text-[#526170]">Guide Relations<select multiple name="guide_relation_ids" defaultValue={selectedGuides} className="mt-2 min-h-40 w-full rounded-xl border border-[#061829]/12 bg-white p-2 text-sm font-semibold outline-none focus:border-[#118cff]">{editor.entityOptions.filter((option) => option.entityType === "GUIDE").map((option) => <option key={option.id} value={option.id}>{option.label}</option>)}</select></label></div></section>
      </> : <section className="p-5 sm:p-6"><SectionTitle title="Gemeinsame Navigation für Desktop und Mobile" copy="Eine Quelle steuert beide Darstellungen. Ziele stammen ausschließlich aus derselben City und aktivem Content." /><div className="mt-4"><NavigationEditor name="navigation_items" initial={editor.navigationItems} targetOptions={editor.targetOptions} /></div></section>}
      <div className="border-t border-[#061829]/10 bg-[#f3f8ff] px-5 py-4 sm:px-6"><label className="flex items-start gap-3 text-sm leading-6 text-[#344454]"><input name="confirm_auto_update" type="checkbox" className="mt-1 size-4 accent-[#118cff]" /><span><span className="block font-black">Automatische Pflege ausdrücklich erlauben</span><span className="block text-xs font-medium text-[#617080]">Nur notwendig, wenn ein Feld von MANUAL zurück auf AUTO gesetzt werden soll.</span></span></label></div>
      <div className="flex flex-col gap-3 border-t border-[#061829]/10 bg-[#fafbf9] p-5 sm:flex-row sm:items-center sm:justify-end sm:p-6"><PendingSubmitButton name="intent" value="draft" pendingLabel="Entwurf wird gespeichert …" className={secondaryButton}>Als Entwurf speichern</PendingSubmitButton><PendingSubmitButton name="intent" value="active" pendingLabel="Änderung wird aktiviert …" className={primaryButton}>Speichern & aktivieren</PendingSubmitButton></div>
    </form>

    <AuditPanel editor={editor} surface={route.surface} />
  </AdminShell>
}

function ControlledField({ label, field, editor, children }: { label: string; field: string; editor: NonNullable<Awaited<ReturnType<typeof loadCitySurfaceEditor>>>; children: ReactNode }) { const mode = editor.fieldControls[field]?.mode ?? "AUTO"; return <label className="grid gap-2 text-xs font-bold text-[#526170]"><span className="flex flex-wrap items-center justify-between gap-2">{label}<FieldModeSelect fieldPath={field} mode={mode} /></span>{children}</label> }
function SectionTitle({ title, copy }: { title: string; copy?: string }) { return <div><h3 className="text-lg font-black tracking-[-.025em]">{title}</h3>{copy ? <p className="mt-1 max-w-3xl text-sm leading-6 text-[#617080]">{copy}</p> : null}</div> }
function Metric({ label, value }: { label: string; value: string }) { return <div className="border-white/10 px-5 py-5 sm:border-l sm:first:border-l-0"><p className="truncate text-lg font-black">{value}</p><p className="mt-1 text-xs font-semibold text-white/60">{label}</p></div> }
function Feedback({ success, code }: { success?: boolean; code: string }) { const message = success ? code === "restored" ? "Vorheriger Wert wiederhergestellt. Dieser Restore wurde als neuer Audit-Eintrag gespeichert." : "Gespeichert. Die öffentliche PRELAUNCH-Seite verwendet die aktive Datenquelle beim nächsten Abruf." : `Vorgang nicht abgeschlossen (${code}). Bitte Eingaben und Berechtigungen prüfen.`; return <div role={success ? "status" : "alert"} className={`rounded-2xl border px-4 py-3 text-sm font-semibold ${success ? "border-emerald-200 bg-emerald-50 text-emerald-900" : "border-rose-200 bg-rose-50 text-rose-900"}`}>{message}</div> }
function groupedTargets(options: CitySafeTargetOption[]) { return [...new Set(options.map((option) => option.group))].map((group) => <optgroup key={group} label={group}>{options.filter((option) => option.group === group).map((option) => <option key={option.key} value={option.key}>{option.label}</option>)}</optgroup>) }
function cityCollectionOptions() { return ["sehenswuerdigkeiten", "freizeit", "natur-ausfluege", "sport", "familie", "schlechtwetter", "wellness-beauty", "shopping", "services"].map((key) => <option key={key} value={key}>{key.replaceAll("-", " ")}</option>) }
const filterOptions = [{ key: "category", label: "Kategorie" }, { key: "duration", label: "Dauer" }, { key: "distance", label: "Entfernung" }, { key: "family", label: "Für Familien" }, { key: "price", label: "Kosten" }, { key: "map", label: "Karte" }]
function prettyKey(value: string) { return value.replaceAll("-", " ").replace(/\b\w/g, (character) => character.toUpperCase()) }
function mediaEntityType(scopeType: string) { return scopeType === "HOMEPAGE" ? "CITY_HOMEPAGE" : scopeType }
function previewUrl(citySlug: string, scopeType: string, scopeKey: string) { const base = `${process.env.NEXT_PUBLIC_BENEFITSI_CITY_BASE_URL?.trim() || process.env.NEXT_PUBLIC_BENEFITSI_WEB_URL?.trim() || "https://benefitsi.de"}`.replace(/\/$/, ""); if (scopeType === "HOMEPAGE") return `${base}/stadt/${citySlug}`; if (scopeType === "HUB") return `${base}/stadt/${citySlug}/${scopeKey === "current" ? "aktuell" : scopeKey === "discovery" ? "entdecken" : scopeKey === "events-community" ? "veranstaltungen" : scopeKey === "routes-guides" ? "routen" : scopeKey === "city-service" ? "stadtwissen" : "vorteile"}`; if (scopeType === "COLLECTION") return `${base}/stadt/${citySlug}/${scopeKey === "sehenswuerdigkeiten" ? "sehenswuerdigkeiten" : `entdecken/${scopeKey}`}`; return `${base}/stadt/${citySlug}` }
function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? "–" : new Intl.DateTimeFormat("de-DE", { dateStyle: "medium", timeStyle: "short" }).format(date) }
function AuditPanel({ editor, surface }: { editor: NonNullable<Awaited<ReturnType<typeof loadCitySurfaceEditor>>>; surface: CitySurfaceType }) { if (!editor.config || !editor.audits.length) return <section className="rounded-3xl border border-dashed border-[#061829]/15 bg-white p-5 sm:p-6"><SectionTitle title="Restore" copy="Nach dem ersten Speichern erscheinen hier die letzten Feldänderungen und sichere Wiederherstellungen." /></section>; return <section className="rounded-3xl border border-[#061829]/10 bg-white p-5 sm:p-6"><SectionTitle title="Restore / letzte Änderungen" copy="Restore überschreibt keine Historie, sondern erzeugt einen neuen Audit-Eintrag." /><div className="mt-4 divide-y divide-[#061829]/10">{editor.audits.slice(0, 12).map((audit) => <div key={audit.id} className="flex flex-col gap-3 py-4 md:flex-row md:items-center md:justify-between"><div className="min-w-0"><p className="text-sm font-black">{audit.fieldPath} · {audit.action}</p><p className="mt-1 text-xs text-[#71808b]">{formatDate(audit.createdAt)} · {audit.actorProfile || "Admin"} · vorher: {shortValue(audit.beforeValue)}</p></div>{audit.action !== "RESTORE" ? <form action={restoreCitySurfaceField}><input type="hidden" name="citySlug" value={editor.city.slug} /><input type="hidden" name="surface" value={surface} /><input type="hidden" name="scopeKey" value={editor.scopeKey} /><input type="hidden" name="auditId" value={audit.id} /><button className={secondaryButton}>Diesen Wert wiederherstellen</button></form> : null}</div>)}</div></section> }
function shortValue(value: unknown) { const raw = typeof value === "string" ? value : JSON.stringify(value); return (raw || "leer").slice(0, 120) }
