import type { SupabaseClient } from '@supabase/supabase-js'
// requestKey is generated by the trusted action, never supplied by the browser.
export async function runMeteredImport<T>(
  client: SupabaseClient,
  partnerId: string,
  requestKey: string,
  extract: () => Promise<T>,
  finish: (
    partner: string,
    reservation: string,
    success: boolean,
  ) => Promise<void>,
): Promise<T> {
  const { data, error } = await client.rpc('reserve_partner_menu_ai_import', {
    p_partner_id: partnerId,
    p_request_key: requestKey,
  })
  if (error || !data?.reservation_id)
    throw new Error(error?.message ?? 'Kontingent nicht verfügbar.')
  if (data.state !== 'reserved')
    throw new Error('Dieser Import wurde bereits bearbeitet.')
  let draft: T
  try {
    draft = await extract()
  } catch (error) {
    await finish(partnerId, data.reservation_id, false)
    throw error
  }
  // Do not release successful provider work if finalization fails. Reconcile it server-side.
  await finish(partnerId, data.reservation_id, true)
  return draft
}
